sudo: required
services:
  - docker
notifications:
  email: false
  
before_install:
- 'chmod 777 build.sh'

script:
- "docker run -i -v \"${PWD}:/MyProgram\" zerotier/centos7-32bit:latest /bin/bash -c \"linux32 --32bit i386 /MyProgram/build.sh\""
